spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    #    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .html